### PR TITLE
Fix RMT::Downloader cache mechanism

### LINKED ISSUE #628: RMT issue with cached repomd.xml
With the new error summary in RMT, we noticed that our RMT had some issues in mirroring specific repositories:

```
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: The following errors occurred while mirroring:
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLES12-Updates' (777): Error while mirroring metadata: GPG key import failed.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SUSE-CAASP-ALL-Pool' (1396): Error while mirroring license: license.de.txt - HTTP request failed with code 404.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLES12-SP4-Pool' (1676): Error while mirroring metadata: repodata/c51296a07949d055b5cb0514435bde14799a6f175e28786d38109a9951b5ade5-license.tar.gz - HTTP request failed with code 404.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-SDK12-SP4-Pool' (1684): Error while mirroring metadata: repodata/b08ac7def1dacefa1b1cad35554c9d0e91c4c955a167d04ea9f63c0f556ef93e-license.tar.gz - HTTP request failed with code 40>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Product-SLES15-SP1-Pool' (3235): Error while mirroring metadata: repodata/35b85bdc30476fd5e2adff6337d546ed341622bfc77288f27d9258f8fb8550d3-primary.xml.gz - HTTP request failed wit>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Basesystem15-SP1-Pool' (3239): Error while mirroring metadata: repodata/35b85bdc30476fd5e2adff6337d546ed341622bfc77288f27d9258f8fb8550d3-primary.xml.gz - HTTP request faile>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Desktop-Applications15-SP1-Pool' (3244): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP reque>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-DevTools15-SP1-Pool' (3249): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request failed wi>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-CAP-Tools15-SP1-Pool' (3254): Error while mirroring metadata: GPG signature verification failed.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Containers15-SP1-Pool' (3259): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request failed >
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Server-Applications15-SP1-Pool' (3264): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP reques>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Web-Scripting15-SP1-Pool' (3274): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request fail>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Legacy15-SP1-Pool' (3279): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request failed with>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Public-Cloud15-SP1-Pool' (3284): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request faile>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SUSE-PackageHub-12-SP4-Pool' (3658): Error while mirroring metadata: GPG signature verification failed.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Transactional-Server15-SP1-Pool' (3821): Error while mirroring metadata: repodata/48ff07ca9da787d67fdb63c2205515253ca39067b489a6f9ec634c382c346464-primary.xml.gz - HTTP req>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Python2-15-SP1-Pool' (5122): Error while mirroring metadata: repodata/2f9f073e5b35fef5409f1e2bdb6fffcc411e7c5655a6aaa23e7e224d479ed285-primary.xml.gz - HTTP request failed >
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Mirroring completed with errors.
Sep 15 03:57:14 rmt systemd[1]: rmt-server-mirror.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 03:57:14 rmt systemd[1]: rmt-server-mirror.service: Unit entered failed state.
Sep 15 03:57:14 rmt systemd[1]: rmt-server-mirror.service: Failed with result 'exit-code'.
```

Under a closer examination, the `repomd.xml` files for these repositories had older content, but the timestamps of the files were newer than their `last-modified` response header. RMT uses this header to save time/bandwidth in the mirroring process. In this case, the timestamp is wrong and actively prevents RMT from fixing its data. I wasn't able to see how this exactly happened, it could have been many things, but we could improve on the process and make RMT more resilient to this type of failure.

One possible option that I saw to fix this could be to use the `etag` [response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag). The servers provide it and we can use it as a mechanism to always download the latest files.

### PR DESCRIPTION
**Pull request by lcaparroz**
## Description

`RMT::Downloader` decided whether to download a file or copy it from cache based on a combination of the file timestamp and the HTTP header `'If-Modified-Since'`: if the file timestamp on disk is newer than on
server, the HTTP response code would be 304 (not modified).

This caused some unexpected behavior if, accidentally, the file timestamp on disk changed. The timeline example below better illustrates the bug:

1. The first time 'repomd.xml' is downloaded from a repo, its `mtime` attribute on the RMT server is correct, since it's been just created;
2. A new version of 'repomd.xml' has been released and is available for mirroring;
3. Accidentally, the file's `mtime` on the RMT server changed to a time newer than the new 'repomd.xml' timestamp on the repo;
4. The next time RMT server tries to mirror `repomd.xml`, it sends a request with the header `'If-Modified-Since'` containing the newer `mtime`, which causes the response HTTP code to be 304;
5. Then, RMT decides to use the cached version of `repomd.xml`, which is outdated;
6. However, since 'repomd.xml' is outdated, when RMT parses it, probably the other files listed in it are no more available (the other `.xml` metadata files are named after their checksum);
7. Mirroring the repository will fail with some HTTP responses 404.

What has changed to avoid trouble with accidental 'mtime' messing:

* Instead of making a "greater than or equal to" comparison using the `'If-Modified-Since'` header, RMT makes a `HEAD` request and compare the `Last-Modified` header with the file `mtime`, deciding to download the file if those are different;
* RMT overwrites the file's `mtime` on disk after downloading with the value of the `'Last-Modified'` header.

Fixes #628.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/137624/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 74d48df1c49c8edc775478aa1e4d20fbb802577d into f010687a6f9ec117811e3ed892cd509339b0a705)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/138418/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 74d48df1c49c8edc775478aa1e4d20fbb802577d into 8bf6dc45c70f0efce10044563fd7e2bdd6378c51)

File: lib/rmt/downloader.rb [hunk 1]
```diff
@@ -89,72 +83,99 @@ def create_fiber_request(local_filenames, file_reference, failed_downloads: nil)
...
+      next failed_files << file.local_path if ignore_errors
+
+      raise e
+    end
+
+    [uncached_files, failed_files]
+  end
+
+  def head_request(file)
+    RMT::HttpRequest.new(request_uri(file).to_s, method: :head, followlocation: true)
```
Comment (tmuntaner) [inline lib/rmt/downloader.rb:146]: Do you think that we need to guard this function to ensure the head request is for http/https?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/138628/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f589cc137cd6e80b730876772fcfabc0ffd44911 into 8bf6dc45c70f0efce10044563fd7e2bdd6378c51)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/138645/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 84ac25a75ca0cb2902e2a4089397ac21169cdd3f into 8bf6dc45c70f0efce10044563fd7e2bdd6378c51)

File: lib/rmt/downloader.rb [hunk 2]
```diff
@@ -89,72 +83,104 @@ def create_fiber_request(local_filenames, file_reference, failed_downloads: nil)
...
-        request.response.code
-      )
+      raise http_error(request.remote_file, request.response.code)
     end
 
     handle_checksum_verification!(file.checksum_type, file.checksum, request.download_path)
 
     FileUtils.mv(request.download_path.path, file.local_path)
     File.chmod(0o644, file.local_path)
+    if (last_modified = request.response.headers['Last-Modified'])
```
Comment (tmuntaner) [inline lib/rmt/downloader.rb:174]: I think that this if statement could become confusing because the `if something = something-else` looks like a bug and hides the intention of the statement.

File: spec/lib/rmt/downloader_spec.rb [hunk 3]
```diff
@@ -365,5 +408,42 @@
         expect(downloader.instance_variable_get(:@queue)).to eq([])
       end
     end
+
+    context 'when there are cached files' do
+      let(:cache_dir) { Dir.mktmpdir }
+
+      context 'when a HEAD request fails and the ignore_erros = false' do
```
Comment (tmuntaner) [inline spec/lib/rmt/downloader_spec.rb:415]:
```suggestion
      context 'when a HEAD request fails and the ignore_errors = false' do
```

File: spec/lib/rmt/downloader_spec.rb [hunk 4]
```diff
@@ -365,5 +408,42 @@
...
+        it 'raises an error' do
+          expect { downloader.download_multi(queue.dup, ignore_errors: false) }
+            .to raise_error(
+              RMT::Downloader::Exception,
+              %r{http://example.com/package[1-3] - HTTP request failed with code 404}
+            )
+        end
+      end
+
+      context 'when a HEAD request fails and the ignore_erros = true' do
```
Comment (tmuntaner) [inline spec/lib/rmt/downloader_spec.rb:433]:
```suggestion
      context 'when a HEAD request fails and the ignore_errors = true' do
```

File: spec/lib/rmt/downloader_spec.rb [hunk 5]
```diff
@@ -365,5 +408,42 @@
...
+        before do
+          queue.each do |file|
+            FileUtils.touch(file.cache_path)
+            stub_request(:head, file.remote_path.to_s).with(headers: headers)
+              .to_return(status: 404, body: 'Not Found', headers: {})
+          end
+        end
+
+        it 'raises an error' do
```
Comment (tmuntaner) [inline spec/lib/rmt/downloader_spec.rb:442]: It doesn't raise an error though.

**Review by tmuntaner — APPROVED** [review]
looks good to me

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/138663/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e328a6397f3361dd4bf3c57273a71e718685acd9 into 8bf6dc45c70f0efce10044563fd7e2bdd6378c51)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/138664/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f8d68f0950a703b5d33ef3671c3aa1980c27e417 into 30ff08deadc2fac859f8917560f2c19245456d32)
