### PR TITLE
Fix rmt cli mirror exit code

### LINKED ISSUE #334: `rmt-cli mirror` doesn't set exit code on errors, unit doesn't enter failed state
Currently `rmt-cli mirror` continues to mirror repositories even if errors are encountered. However, it doesn't set exit code if errors were encountered, as the result `systemd` unit doesn't enter failed state. It is hard to tell if mirroring was successful or not, there are a lot of info messages displayed and it's hard to find error messages.

SMT displayed error summary at the very end with the list of repositories that weren't fully mirrored.

```
● rmt-server-mirror.service - Mirror RMT
   Loaded: loaded (/usr/lib/systemd/system/rmt-server-mirror.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Tue 2019-02-12 18:46:38 CET; 3s ago
  Process: 454 ExecStart=/usr/share/rmt/bin/rmt-cli mirror (code=exited, status=0/SUCCESS)
 Main PID: 454 (code=exited, status=0/SUCCESS)

Feb 12 18:46:37 e127 systemd[1]: Started Mirror RMT.
Feb 12 18:46:38 e127 rmt-cli[454]: INFO: RMT version 1.1.1
Feb 12 18:46:38 e127 rmt-cli[454]: INFO: Mirroring repository SLE-Module-Toolchain12-Pool to /usr/share/rmt/public/repo/SUSE/Products/SLE-Module-Toolchain/12/x86_64/product/
Feb 12 18:46:38 e127 rmt-cli[454]: WARN: Error while mirroring metadata: repodata/repomd.xml - return code ssl_cacert
Feb 12 18:46:38 e127 rmt-cli[454]: INFO: Mirroring repository SLE-Module-Toolchain12-Updates to /usr/share/rmt/public/repo/SUSE/Updates/SLE-Module-Toolchain/12/x86_64/update/
Feb 12 18:46:38 e127 rmt-cli[454]: WARN: Error while mirroring metadata: repodata/repomd.xml - return code ssl_cacert
```

### PR DESCRIPTION
**Pull request by lcaparroz**
## Description

The command `rmt-cli mirror` and all its subcommands would not exit with status code `1` if any repository failed to be mirrored, then  the `systemd` unit service couldn't enter failed state.

Fixes #334.

## Change Type

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/131345/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 7f2bc38c466ce8dd5e4c611c0d54347457ecad45)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/131518/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 7f2bc38c466ce8dd5e4c611c0d54347457ecad45)

File: lib/rmt/cli/mirror.rb [hunk 1]
```diff
@@ -70,34 +68,51 @@ def product(*targets)
...
-    repo.refresh_timestamp!
+    [mirrored_repo_ids, errors]
   end
 
+  def handle_errors!(errors)
+    return if errors.empty?
 
+    raise RMT::CLI::Error.new(
+      _('The following errors ocurred while mirroring:%{errors_list}') % {
+        errors_list: "\n" + errors.join("\n")
```
Comment (tmuntaner) [inline lib/rmt/cli/mirror.rb:114]: I think that we probably want one extra \n at the start. Also, we could consider colors like

```
def handle_errors!(errors)
    return if errors.empty?

    raise RMT::CLI::Error.new(
      _('The following errors ocurred while mirroring:%{errors_list}') % {
        errors_list: "\n\e[31m" + errors.join("\n") + "\e[0m"
      }
    )
  end
```

Also, consider having a "mirroring complete" message.

**Review by tmuntaner — COMMENTED** [review]
Looks good so far.

During the tests, let's also check for error code 0 when everything goes right.

File: lib/rmt/cli/mirror.rb [hunk 2]
```diff
@@ -70,34 +68,51 @@ def product(*targets)
...
   protected
 
-  def mirror_repo!(mirror, repo)
-    mirror.mirror(
-      repository_url: repo.external_url,
-      local_path: Repository.make_local_path(repo.external_url),
-      auth_token: repo.auth_token,
-      repo_name: repo.name
-    )
+  def mirror_repos!(mirror, repos)
```
Comment (tmuntaner) [inline lib/rmt/cli/mirror.rb:86]: Do we still need to call this `mirror_repos!`? Maybe, no with it not raising errors anymore, we could call it `mirror_repos`.

Comment (lcaparroz) [reply lib/rmt/cli/mirror.rb:86]: Previously, it was `mirror_repo!` and it had no error raising statements, my guess is it had the exclamation because it would modify the repository objects with `repo.refresh_timestamp!`.

I can change it.

Comment (tmuntaner) [reply lib/rmt/cli/mirror.rb:86]: Wait, you may be right with the refresh_timestamp! You can ignore my comment ^_^

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131574/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 8a2d4c3b42841bcb2d5a63a2b1cbf74d47f7acb0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132839/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 79e90aaf46968ec89a74ff14b3269415eab499df)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132840/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 11ab5adadb9679957a9a1a45dfa8420720df064c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132841/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into bea2a88b046943eff8f7bf90b352585c61847eaf)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132981/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 6fc1d330974b42765d6ee037f7d59ae28b824d85)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132982/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 8a421d990f8b50d9582c16e2eda156eb576d4279)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133153/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1a1b1660018a34d724b9ac33d1020aa80c8e9397 into 009e6c36528eab860ec50a254724121ac9bf0236)

**Review by tmuntaner — APPROVED** [review]
Looks good to me when combined with #620

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133154/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a8f5565b4e89674c18f91239660fe84e3f20a982 into 009e6c36528eab860ec50a254724121ac9bf0236)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133155/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7c8333d732f1fc2ea31ef95a6545c3a6d35b05f2 into 009e6c36528eab860ec50a254724121ac9bf0236)
